name: Build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@f84c5fc2689c34ca84f4abe8211608924b91bb71 # main
