name: Merge upstream

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: merge-upstream-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_upstream:
    uses: SpiralP/github-reusable-workflows/.github/workflows/merge-upstream.yml@4fefe24af975fe02ec51d4ab1d5624e2e3c4240b # main
    with:
      url: https://github.com/SpiralP/github-reusable-workflows.git
