on:
  workflow_call:

permissions:
  actions: write # to prune cache
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31
      - run: sudo chown -R $(id -u):$(id -g) /nix
      - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
        with:
          primary-key: nix-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-
          gc-max-store-size: 4G
          purge: true
          purge-prefixes: nix-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never
      - run: sudo chown -R 0:0 /nix
      - run: |
          nix run github:SpiralP/github-reusable-workflows#semantic-release \
            --print-build-logs --no-write-lock-file --recreate-lock-file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
