on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        description: Runner to use for the job.
        required: false
        type: string
      args:
        default: ""
        description: Arguments to pass to semantic-release.
        required: false
        type: string
      extends:
        default: ""
        description: Path to a config file for extending semantic-release.
        required: false
        type: string
    secrets:
      app-id:
        description: GitHub App ID
        required: false
      app-private-key:
        description: GitHub App private key
        required: false
      token:
        description: GitHub token
        required: false

permissions:
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31
        if: ${{ inputs.runs-on != 'self-hosted' }}
      - run: sudo chown -R $(id -u):$(id -g) /nix
        if: ${{ inputs.runs-on != 'self-hosted' }}
      - name: Get workflow SHA
        id: get_workflow_sha
        run: |
          workflow_path="$(printf '%s' '${{ github.workflow_ref }}' | sed 's/[^/]*\/[^/]*\/\([^@]*\).*/\1/')"
          echo "workflow_path=$workflow_path"
          workflow_sha="$(cat "$workflow_path" | grep ' uses: SpiralP/github-reusable-workflows/' | sed 's/.*@\(\S*\).*/\1/')"
          test -z "$workflow_sha" && workflow_sha="main"
          echo "workflow_sha=$workflow_sha"
          echo "workflow_sha=$workflow_sha" >> "$GITHUB_OUTPUT"
      - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
        if: ${{ inputs.runs-on != 'self-hosted' }}
        with:
          primary-key: nix-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.get_workflow_sha.outputs.workflow_sha }}
          restore-prefixes-first-match: nix-${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-
          gc-max-store-size: 5G
      - run: sudo chown -R 0:0 /nix
        if: ${{ inputs.runs-on != 'self-hosted' }}
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        if: ${{ env.OK == 'true-true-true' }}
        env:
          OK: ${{ secrets.token == '' }}-${{ secrets.app-id != '' }}-${{ secrets.app-private-key != '' }}
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.app-private-key }}
      - name: Release
        run: |
          EXTENDS="${{ inputs.extends }}" \
            nix run github:SpiralP/github-reusable-workflows/${{ steps.get_workflow_sha.outputs.workflow_sha }}#semantic-release \
              --print-build-logs \
              -- ${{ inputs.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.token || steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
