on:
  workflow_call:
    inputs:
      flake-attribute:
        default: default
        description: Nix flake attribute path to default output to test build.
        required: false
        type: string
      npm-attribute:
        description: |
          Nix flake attribute path to buildNpmPackage or similar output.
          Leave blank/unspecified to disable running "npm update"
        required: false
        type: string
      npm-manifest-dir:
        default: .
        description: Path to directory containing "package.json" file.
        required: false
        type: string
      rust-attribute:
        description: |
          Nix flake attribute path to buildRustPackage or similar output.
          Leave blank/unspecified to disable running "cargo update"
        required: false
        type: string
      rust-manifest-dir:
        default: .
        description: Path to directory containing "Cargo.toml" file.
        required: false
        type: string

jobs:
  update_lock_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake update
      - run: git diff && git add -v .
      - run: nix develop '.#${{ inputs.rust-attribute }}' --no-update-lock-file --print-build-logs -c cargo update
        if: ${{ inputs.rust-attribute }}
        working-directory: ${{ inputs.rust-manifest-dir }}
      - run: git diff && git add -v .
        if: ${{ inputs.rust-attribute }}
      # TODO maybe delete lock file because `npm update` is strange
      - run: nix develop '.#${{ inputs.npm-attribute }}' --no-update-lock-file --print-build-logs -c npm update
        if: ${{ inputs.npm-attribute }}
        working-directory: ${{ inputs.npm-manifest-dir }}
      - run: git diff && git add -v .
        if: ${{ inputs.npm-attribute }}
      - run: |
          nix run github:SpiralP/github-reusable-workflows#update-nix-hashes \
            --recreate-lock-file --no-write-lock-file \
            -- '${{ inputs.npm-attribute }}' '${{ inputs.npm-manifest-dir }}/package-lock.json'
        if: ${{ inputs.npm-attribute }}
      - run: git diff && git add -v .
        if: ${{ inputs.npm-attribute }}
      - run: |
          nix build '.#${{ inputs.flake-attribute }}' \
            --no-update-lock-file --print-build-logs
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: update-lock-files
          title: Update lock files
          body: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          commit-message: |
            Update lock files

            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
