on:
  workflow_call:
    inputs:
      flake-attribute:
        default: default
        description: Nix flake attribute path to default output to test build.
        required: false
        type: string
      npm-attribute:
        description: Nix flake attribute path to buildNpmPackage or similar output.
        required: true
        type: string
      npm-manifest-dir:
        default: .
        description: Path to directory containing "package.json" file.
        required: false
        type: string

permissions:
  contents: write # to push branch

jobs:
  update_nix_hashes:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31.6.0
      - run: |
          nix run github:SpiralP/github-reusable-workflows#update-nix-hashes \
            --print-build-logs --no-write-lock-file --recreate-lock-file \
            -- '${{ inputs.npm-attribute }}' '${{ inputs.npm-manifest-dir }}/package-lock.json'
      - run: git diff && git add -v .
      - run: |
          nix build '.#${{ inputs.flake-attribute }}' \
            --print-build-logs --no-update-lock-file
      - run: git status && git diff --cached
      - run: 'git commit -m "nix: update hashes" -m "$RUN_URL" || true'
        env:
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - run: git push origin
