on:
  workflow_call:
    inputs:
      flake-attribute:
        default: default
        description: Nix flake attribute path to default output to test build.
        required: false
        type: string
      npm-attribute:
        description: Nix flake attribute path to buildNpmPackage or similar output.
        required: true
        type: string
      npm-manifest-dir:
        default: .
        description: Path to directory containing "package.json" file.
        required: false
        type: string

jobs:
  update_nix_hashes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix run github:SpiralP/github-reusable-workflows#update-nix-hashes \
            --recreate-lock-file --no-write-lock-file \
            -- '${{ inputs.npm-attribute }}' '${{ inputs.npm-manifest-dir }}/package-lock.json'
      - run: git diff && git add -v .
      - run: |
          nix build '.#${{ inputs.flake-attribute }}' \
            --no-update-lock-file --print-build-logs
      - run: git status && git diff --cached
      - run: 'git commit -m "nix: update hashes" -m "$RUN_URL" || true'
        env:
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - run: git push origin
