on:
  workflow_call:
    inputs:
      flake-attribute:
        default: default
        description: Nix flake attribute path to default output to test build.
        required: false
        type: string
      npm-attribute:
        description: |
          Nix flake attribute path to buildNpmPackage or similar output.
          Leave blank/unspecified to disable running "npm update"
        required: false
        type: string
      npm-manifest-dir:
        default: .
        description: Path to directory containing "package.json" file.
        required: false
        type: string
      npm-update-nix-hashes:
        default: false
        description: |
          Update npmDepsHash in flake.nix after running "npm update".
        required: false
        type: boolean
      rust-attribute:
        description: |
          Nix flake attribute path to buildRustPackage or similar output.
          Leave blank/unspecified to disable running "cargo update"
        required: false
        type: string
      rust-manifest-dir:
        default: .
        description: Path to directory containing "Cargo.toml" file.
        required: false
        type: string

permissions:
  contents: write # to push branch
  pull-requests: write # to create pr

# TODO maybe delete and recreate the lock files? `npm update` can be strange and keep deps cached

jobs:
  update_lock_files:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.5.0
      - run: nix flake update
      - run: git diff && git add -v .
      - name: cargo update
        run: |
          nix develop '.#${{ inputs.rust-attribute }}' \
            --print-build-logs --no-update-lock-file \
            -c cargo update
        if: ${{ inputs.rust-attribute }}
        working-directory: ${{ inputs.rust-manifest-dir }}
      - run: git diff && git add -v .
        if: ${{ inputs.rust-attribute }}
      - name: npm update
        run: |
          nix develop '.#${{ inputs.npm-attribute }}' \
            --print-build-logs --no-update-lock-file \
            -c npm update
        if: ${{ inputs.npm-attribute }}
        working-directory: ${{ inputs.npm-manifest-dir }}
      - run: git diff && git add -v .
        if: ${{ inputs.npm-attribute }}
      - run: |
          nix run github:SpiralP/github-reusable-workflows#update-nix-hashes \
            --print-build-logs --no-write-lock-file --recreate-lock-file \
            -- '${{ inputs.npm-attribute }}' '${{ inputs.npm-manifest-dir }}/package-lock.json'
        if: ${{ inputs.npm-attribute && inputs.npm-update-nix-hashes }}
      - run: git diff && git add -v .
        if: ${{ inputs.npm-attribute && inputs.npm-update-nix-hashes }}
      - run: |
          nix build '.#${{ inputs.flake-attribute }}' \
            --print-build-logs --no-update-lock-file
      - run: git status && git diff --cached
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: update-lock-files
          title: Update lock files
          body: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          commit-message: |
            Update lock files

            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
