name: Update nix hashes

on:
  pull_request:
    branches: [master, main]

concurrency:
  group: update-nix-hashes-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update_nix_hashes:
    # !!! disabled
    if: ${{ false }}
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-nix-hashes.yml@f84c5fc2689c34ca84f4abe8211608924b91bb71 # main
    with:
      npm-attribute: node
